# Fonts
font_family         JetBrainsMono Nerd Font 
bold_font           auto
italic_font         auto
bold_italic_fonts   auto
font_size           12.0

# Window layout
window_padding_width 10 

# Background transparency
background_opacity 0.85
dynamic_background_opacity yes

# Blur
background_blur 20

# Tab Bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Only show the tab bar if there is more than one tab
tab_bar_min_tabs 2

# Tab colors (customize these to match your theme!)
active_tab_foreground   #1e1e2e
active_tab_background   #cba6f7
active_tab_font_style   bold-italic
inactive_tab_foreground #bac2de
inactive_tab_background #313244

# Cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval -1


# BEGIN_KITTY_THEME
# Carbonfox
include current-theme.conf
# END_KITTY_THEME
